import os
import subprocess
import sys
import tempfile
import unittest

class TestE2EClaimsOnly(unittest.TestCase):
    def setUp(self):
        self.temp_dir = tempfile.mkdtemp()
        self.file_path = os.path.join(self.temp_dir, "agent_response.md")
        with open(self.file_path, "w", encoding="utf-8") as f:
            f.write("This is a raw text claim generated by an LLM.\n\nIt has no evidence tags.\n")
            
        # Resolve the path to validator.py
        self.validator_script = os.path.abspath(
            os.path.join(os.path.dirname(__file__), "../../../python/validator.py")
        )

    def tearDown(self):
        import shutil
        shutil.rmtree(self.temp_dir)

    def test_claims_only_cli_with_no_print(self):
        """Subprocess E2E: --no-print should keep stdout completely empty."""
        env = os.environ.copy()
        env["ORACLE_RAG_DB_DIR"] = os.path.join(self.temp_dir, "fake_db")
        
        cmd = [
            sys.executable, self.validator_script,
            "--file", self.file_path,
            "--claims-only",
            "--no-print"
        ]
        
        result = subprocess.run(cmd, env=env, capture_output=True, text=True)
        
        self.assertEqual(result.returncode, 0)
        self.assertIn("all claims grounded", result.stderr)
        # TRUE E2E ASSERTION: Stdout must be completely silent
        self.assertEqual(result.stdout.strip(), "", "Stdout should be empty when --no-print is used")

    def test_claims_only_cli_default_prints(self):
        """Subprocess E2E: Omitting --no-print should print the summary to stdout."""
        env = os.environ.copy()
        env["ORACLE_RAG_DB_DIR"] = os.path.join(self.temp_dir, "fake_db")
        
        cmd = [
            sys.executable, self.validator_script,
            "--file", self.file_path,
            "--claims-only"
        ]
        
        result = subprocess.run(cmd, env=env, capture_output=True, text=True)
        
        self.assertEqual(result.returncode, 0)
        self.assertIn("all claims grounded", result.stderr)
        # TRUE E2E ASSERTION: Stdout must contain the summary
        self.assertIn("all claims grounded", result.stdout, "Stdout should contain the summary when --no-print is omitted")


if __name__ == "__main__":
    unittest.main()
