import os
import sys
import tempfile
import unittest
from unittest.mock import patch, MagicMock

# Ensure the python directory is in the path for imports
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "../../../python")))
import oracle_agent

class TestE2EOracleClaims(unittest.TestCase):
    def setUp(self):
        self.temp_dir = tempfile.mkdtemp()
        self.original_cwd = os.getcwd()
        # Run in temp dir to isolate .aider_factory/temp creation
        os.chdir(self.temp_dir) 
        
        os.environ["ORACLE_AGENT_MODEL"] = "dummy-model"
        os.environ["ORACLE_RAG_DB_DIR"] = os.path.join(self.temp_dir, "fake_db")
        
    def tearDown(self):
        os.chdir(self.original_cwd)
        import shutil
        shutil.rmtree(self.temp_dir)
        os.environ.pop("ORACLE_AGENT_MODEL", None)
        os.environ.pop("ORACLE_RAG_DB_DIR", None)
        os.environ.pop("ORACLE_CLAIMS_ONLY", None)
        os.environ.pop("ORACLE_NO_PRINT", None)

    @patch("litellm.completion")
    @patch("validator._verify")
    def test_e2e_oracle_claims_integration(self, mock_verify, mock_completion):
        """
        Tests the full integration from oracle_agent CLI -> LLM -> validator._run_claims_only -> report generation.
        """
        # Force the validator to see the claim as hallucinated (score 0.1 < threshold 0.6)
        mock_verify.return_value = ("cosine", 0.1, [("source.md", "Real source text")], 0.6)
        
        # Mock the LLM response using a standard dict to avoid MagicMock JSON serialization errors
        mock_resp = {
            "choices": [
                {
                    "message": {
                        "content": "This is a hallucinated claim from the Oracle."
                    }
                }
            ],
            "usage": {"prompt_tokens": 10, "completion_tokens": 10}
        }
        
        mock_completion.return_value = mock_resp

        # Simulate CLI arguments
        test_args = ["oracle_agent.py", "--claims-only", "--no-print", "--no-rag", "Tell me a fact."]
        
        with patch.object(sys, 'argv', test_args):
            # Run the oracle agent main function
            rc = oracle_agent.main()
            
        self.assertEqual(rc, 0)
        
        # Verify the report was generated by the validator
        report_path = os.path.join(self.temp_dir, ".aider_factory", "temp", "oracle_claims_report.md")
        self.assertTrue(os.path.exists(report_path), "Validator report was not created by Oracle.")
        
        with open(report_path, "r", encoding="utf-8") as f:
            content = f.read()
            
        # The validator should have processed the Oracle's exact output
        self.assertIn("This is a hallucinated claim from the Oracle.", content)
        self.assertIn("unsupported claims found", content)
