import os
import subprocess
import tempfile
import unittest

class TestE2EClaimsOnly(unittest.TestCase):
    def setUp(self):
        self.temp_dir = tempfile.mkdtemp()
        self.file_path = os.path.join(self.temp_dir, "agent_response.md")
        with open(self.file_path, "w", encoding="utf-8") as f:
            f.write("This is a raw text claim generated by an LLM.\n\nIt has no evidence tags.\n")
            
        # Resolve the path to validator.py
        self.validator_script = os.path.abspath(
            os.path.join(os.path.dirname(__file__), "../../../python/validator.py")
        )

    def tearDown(self):
        import shutil
        shutil.rmtree(self.temp_dir)

    def test_claims_only_cli_execution(self):
        """
        Smoke test to ensure the CLI accepts the --claims-only flag without 
        requiring --source or --report, and executes without crashing.
        """
        env = os.environ.copy()
        # Point to a dummy DB directory so _region gracefully returns None
        env["ORACLE_RAG_DB_DIR"] = os.path.join(self.temp_dir, "fake_db")
        
        cmd = [
            "python3", self.validator_script,
            "--file", self.file_path,
            "--claims-only",
            "--no-print"
        ]
        
        result = subprocess.run(cmd, env=env, capture_output=True, text=True)
        
        # Because the DB is missing, _region returns (None, []). 
        # The logic `if score is not None and score < thr:` safely ignores it.
        # It should exit 0 and print that all claims are grounded.
        self.assertEqual(result.returncode, 0, f"Validator crashed: {result.stderr}")
        self.assertIn("all claims grounded", result.stderr)
        
        # Verify the auto-generated report path was printed to stderr
        self.assertIn("agent_response", result.stderr)
