#!/usr/bin/env python3
"""True End-to-End Smoke Test for YAML Configuration and Live Embeddings.

This test uses zero mocks for embedding or retrieval. It hits the live network
endpoints, creates a real LanceDB database on disk, and verifies that the
Oracle successfully retrieves verbatim chunks.
"""

import os
import shutil
import sys
import tempfile
import unittest
import yaml

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "../../../python")))
import rag_manager
import oracle_agent

class TestE2EYamlOracle(unittest.TestCase):
    def setUp(self):
        self.temp_dir = tempfile.mkdtemp()
        self.old_cwd = os.getcwd()
        os.chdir(self.temp_dir)

        # Clean environment variables
        for k in list(os.environ.keys()):
            if k.startswith("ORACLE_"):
                del os.environ[k]

    def tearDown(self):
        os.chdir(self.old_cwd)
        shutil.rmtree(self.temp_dir, ignore_errors=True)

    def _run_live_yaml_test(self, api_base, model_name, collection_name):
        # Probe endpoint connectivity first
        try:
            import requests
            requests.get(f"{api_base}/models", timeout=5).raise_for_status()
        except Exception:
            self.skipTest(f"Live embedding endpoint at {api_base} is offline.")

        # 1. Create .env.yml simulating the exact user configuration
        env_yml = {
            "endpoints": {
                "embed_api_base": api_base
            },
            "phases": [{
                "name": "Test Phase",
                "enabled": True,
                "models": {
                    "embed_model": model_name
                },
                "rag": {
                    "collection_name": collection_name,
                    "embed_backend": "sentence-transformers",
                    "batch": True
                }
            }]
        }
        with open(".env.yml", "w") as f:
            yaml.dump(env_yml, f)

        # 2. Use the real PDF document for true end-to-end testing
        script_dir = os.path.dirname(os.path.abspath(__file__))
        source_pdf = os.path.join(script_dir, "January-2026-FX-Report.pdf")
        
        if not os.path.exists(source_pdf):
            self.skipTest(f"Source PDF not found at {source_pdf}")

        job_dir = os.path.join(self.temp_dir, ".aider_factory", "markdown", "lanceDB", collection_name)
        os.makedirs(job_dir, exist_ok=True)
        dest_pdf = os.path.join(job_dir, "January-2026-FX-Report.pdf")
        shutil.copy2(source_pdf, dest_pdf)

        # 3. Run LIVE RAG Ingestion using the YAML config (PDF -> Docling -> MD -> LanceDB)
        success = rag_manager._from_config(".env.yml")
        self.assertTrue(success, f"RAG Ingestion failed for {collection_name}!")

        # Verify the markdown sidecar was actually generated by the ingestion pipeline
        md_path = os.path.join(job_dir, "January-2026-FX-Report.md")
        self.assertTrue(os.path.exists(md_path), "Markdown sidecar was not generated from the PDF!")

        # 4. Configure Oracle Environment exactly as the CLI would
        os.environ["ORACLE_CONFIG_FILE"] = os.path.abspath(".env.yml")
        oracle_agent._extract_overrides(["--collection", collection_name])
        oracle_agent._ensure_oracle_config()

        # Assertions: Verify the system coerced the backend correctly
        self.assertEqual(os.environ.get("ORACLE_EMBED_BACKEND"), "openai")
        self.assertEqual(os.environ.get("ORACLE_EMBED_API_BASE"), api_base)

        # 5. Run LIVE Oracle Retrieval for a query that spans multiple chunks
        query = "What happened to the U.S. current account deficit and annual inflation?"
        context = oracle_agent._retrieve(query, k=3)

        print(f"\n============================================================")
        print(f"VERBATIM RETRIEVED CHUNKS ({collection_name} | {model_name}):")
        print(f"============================================================")
        print(context)
        print(f"============================================================\n")

        self.assertTrue(bool(context), "Oracle retrieved 0 chunks from the database!")
        self.assertTrue(
            "tariffs" in context.lower() or "labor" in context.lower() or "pdfp" in context.lower(),
            f"Expected top-k chunks to contain economic metrics, got:\n{context}"
        )
        
        # Count the number of chunks returned
        chunk_count = context.count("[source:")
        self.assertTrue(chunk_count >= 1, f"Expected chunks, but got {chunk_count}")

    def test_yaml_config_node1_live(self):
        self._run_live_yaml_test(
            api_base="http://192.168.100.1:8080/v1",
            model_name="qwen3-embedding-8b-8k-gpu:LATEST",
            collection_name="YAML_Node1_DB"
        )

    def test_yaml_config_router_live(self):
        self._run_live_yaml_test(
            api_base="http://192.168.100.2:8081/v1",
            model_name="qwen3-embedding-8b-8k:LATEST",
            collection_name="YAML_Router_DB"
        )

if __name__ == "__main__":
    unittest.main()
